### ISSUE TITLE
Android 13

### ISSUE THREAD

**Issue by baraa272** [Magisk-Modules-Alt-Repo/NoStorageRestrict#12] opened 2022-09-21 21:31 UTC
Latest module version 3 make "Files" see no files and folders on External SD card when I choose SAF way to give applications access to some folders

**Comment by DanGLVK** [comment] 2022-09-21 21:35
> Latest module version 3 make "Files" see no files and folders on External SD card when I choose SAF way to give applications access to some folders

Could you check if the Xposed version in the module's description works?

**Comment by DanGLVK** [comment] 2022-09-21 21:37
> Latest module version 3 make "Files" see no files and folders on External SD card when I choose SAF way to give applications access to some folders



> Latest module version 3 make "Files" see no files and folders on External SD card when I choose SAF way to give applications access to some folders

Also after uninstalling the Magisk module and rebooting could you provide me the external storage manager APK from your device? I believe the issue is being caused due to me using the APK from the Android 13 beta's

**Comment by baraa272** [comment] 2022-09-22 16:23
I use magisk module not xposed

**Comment by baraa272** [comment] 2022-09-22 16:26
Android 13 beta here 
Here is link 
https://files.catbox.moe/1ddd2s.apk

**Comment by DanGLVK** [comment] 2022-09-22 16:28
> I use magisk module not xposed

I just asked if you could try the Xposed module to see if it works out for you

**Comment by baraa272** [comment] 2022-09-22 16:29
Ok ok 
Installed hope it works

**Comment by baraa272** [comment] 2022-09-22 16:32
It works 
Seems xposed works for now

**Comment by baraa272** [comment] 2022-09-22 16:33
![Uploading Screenshot_20220922-193320.png…]()

**Comment by baraa272** [comment] 2022-09-22 16:34
![Screenshot_20220922-193320](https://user-images.githubusercontent.com/32843097/191802911-090c4e54-d061-4396-bcf5-87d4f688457c.png)

**Comment by DanGLVK** [comment] 2022-09-22 16:38
> ![Screenshot_20220922-193320](https://user-images.githubusercontent.com/32843097/191802911-090c4e54-d061-4396-bcf5-87d4f688457c.png)

[NoStorageRestrict-main.zip](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict/files/9627745/NoStorageRestrict-main.zip)


Alright here's the updated Magisk module if you wish to try it

**Comment by baraa272** [comment] 2022-09-22 16:51
Ok will test later and report

**Comment by baraa272** [comment] 2022-09-22 16:57
Installed through fox Mmm and that didnt work 
![Screenshot_20220922-195701_Files](https://user-images.githubusercontent.com/32843097/191807390-837df20d-95a4-4e5b-93be-74ddf827bf01.png)

**Comment by DanGLVK** [comment] 2022-09-22 17:15
> Installed through fox Mmm and that didnt work ![Screenshot_20220922-195701_Files](https://user-images.githubusercontent.com/32843097/191807390-837df20d-95a4-4e5b-93be-74ddf827bf01.png)

[NoStorageRestrict-main.zip](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict/files/9628028/NoStorageRestrict-main.zip)

Try this, I've implemented a different method than before, now it more closely resembles the Xposed module

**Comment by baraa272** [comment] 2022-09-22 19:07
Ok let's see

**Comment by baraa272** [comment] 2022-09-22 19:11
It works now 
![Screenshot_20220922-221109_Files](https://user-images.githubusercontent.com/32843097/191831693-e1077483-7d36-4b82-819a-28f7669efd60.png)

**Comment by DanGLVK** [comment] 2022-09-22 19:14
> It works now ![Screenshot_20220922-221109_Files](https://user-images.githubusercontent.com/32843097/191831693-e1077483-7d36-4b82-819a-28f7669efd60.png)

Great, thanks for testing, i'll push an official update soon

**Comment by DanGLVK** [comment] 2022-09-22 19:24
I'll now be closing this issue, if you need anything else i'll reopen it

**Closed as completed by DanGLVK** 2022-09-22 19:24 UTC

**Comment by baraa272** [comment] 2022-09-22 19:50
All love and respect man
